-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.analytics_message_analysis (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  message_id uuid,
  sentiment character varying,
  sentiment_score numeric,
  intent_categories jsonb DEFAULT '[]'::jsonb,
  entities jsonb DEFAULT '{}'::jsonb,
  keywords jsonb DEFAULT '[]'::jsonb,
  language_code character varying,
  language_confidence numeric,
  ai_provider character varying,
  ai_model character varying,
  prompt_tokens integer,
  completion_tokens integer,
  total_tokens integer,
  processing_time_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT analytics_message_analysis_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_message_analysis_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.whatsapp_messages(id)
);
CREATE TABLE public.clickup_contact_mapping (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contact_id uuid UNIQUE,
  clickup_user_id character varying,
  clickup_email character varying,
  clickup_username character varying,
  clickup_initials character varying,
  clickup_color character varying,
  clickup_profile_picture text,
  sync_enabled boolean DEFAULT true,
  custom_field_mappings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clickup_contact_mapping_pkey PRIMARY KEY (id),
  CONSTRAINT clickup_contact_mapping_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.whatsapp_contacts(id)
);
CREATE TABLE public.clickup_folders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  space_id uuid,
  folder_id character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  orderindex integer,
  override_statuses boolean DEFAULT false,
  hidden boolean DEFAULT false,
  task_count integer DEFAULT 0,
  lists jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clickup_folders_pkey PRIMARY KEY (id),
  CONSTRAINT clickup_folders_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.clickup_spaces(id)
);
CREATE TABLE public.clickup_lists (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  folder_id uuid,
  space_id uuid,
  list_id character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  orderindex integer,
  status jsonb DEFAULT '{}'::jsonb,
  priority jsonb DEFAULT '{}'::jsonb,
  assignee text,
  due_date_time boolean DEFAULT false,
  start_date_time boolean DEFAULT false,
  archived boolean DEFAULT false,
  override_statuses boolean DEFAULT false,
  permission_level character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clickup_lists_pkey PRIMARY KEY (id),
  CONSTRAINT clickup_lists_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.clickup_spaces(id),
  CONSTRAINT clickup_lists_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES public.clickup_folders(id)
);
CREATE TABLE public.clickup_spaces (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workspace_id uuid,
  space_id character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  color character varying,
  private boolean DEFAULT false,
  avatar text,
  admin_can_manage boolean,
  multiple_assignees boolean,
  features jsonb DEFAULT '{}'::jsonb,
  archived boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clickup_spaces_pkey PRIMARY KEY (id),
  CONSTRAINT clickup_spaces_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.clickup_workspaces(id)
);
CREATE TABLE public.clickup_tasks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  list_id uuid,
  task_id character varying NOT NULL UNIQUE,
  custom_id character varying,
  name character varying NOT NULL,
  text_content text,
  description text,
  status USER-DEFINED,
  orderindex character varying,
  date_created timestamp with time zone,
  date_updated timestamp with time zone,
  date_closed timestamp with time zone,
  date_done timestamp with time zone,
  archived boolean DEFAULT false,
  creator character varying,
  assignees jsonb DEFAULT '[]'::jsonb,
  watchers jsonb DEFAULT '[]'::jsonb,
  checklists jsonb DEFAULT '[]'::jsonb,
  tags jsonb DEFAULT '[]'::jsonb,
  parent character varying,
  priority USER-DEFINED,
  due_date timestamp with time zone,
  start_date timestamp with time zone,
  points numeric,
  time_estimate integer,
  time_spent integer DEFAULT 0,
  custom_fields jsonb DEFAULT '{}'::jsonb,
  dependencies jsonb DEFAULT '[]'::jsonb,
  linked_tasks jsonb DEFAULT '[]'::jsonb,
  team_id character varying,
  url text,
  permission_level character varying,
  attachments jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clickup_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT clickup_tasks_list_id_fkey FOREIGN KEY (list_id) REFERENCES public.clickup_lists(id)
);
CREATE TABLE public.clickup_webhook_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workspace_id uuid,
  webhook_id character varying,
  event character varying NOT NULL,
  task_id character varying,
  history_items jsonb DEFAULT '[]'::jsonb,
  payload jsonb NOT NULL,
  processed boolean DEFAULT false,
  processed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clickup_webhook_events_pkey PRIMARY KEY (id),
  CONSTRAINT clickup_webhook_events_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.clickup_workspaces(id)
);
CREATE TABLE public.clickup_workspaces (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid,
  team_id character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  color character varying,
  avatar text,
  members jsonb DEFAULT '[]'::jsonb,
  access_token text,
  webhook_id character varying,
  webhook_secret character varying,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clickup_workspaces_pkey PRIMARY KEY (id),
  CONSTRAINT clickup_workspaces_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  whatsapp_business_account_id character varying,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid,
  email character varying NOT NULL UNIQUE,
  full_name character varying NOT NULL,
  avatar_url text,
  role character varying DEFAULT 'agent'::character varying,
  is_active boolean DEFAULT true,
  preferences jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.whatsapp_contacts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid,
  wa_id character varying NOT NULL UNIQUE,
  profile_name character varying,
  formatted_name character varying,
  first_name character varying,
  last_name character varying,
  middle_name character varying,
  suffix character varying,
  prefix character varying,
  birthday date,
  phones jsonb DEFAULT '[]'::jsonb,
  emails jsonb DEFAULT '[]'::jsonb,
  urls jsonb DEFAULT '[]'::jsonb,
  addresses jsonb DEFAULT '[]'::jsonb,
  org_name character varying,
  org_department character varying,
  org_title character varying,
  tags ARRAY DEFAULT '{}'::text[],
  custom_fields jsonb DEFAULT '{}'::jsonb,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT whatsapp_contacts_pkey PRIMARY KEY (id),
  CONSTRAINT whatsapp_contacts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.whatsapp_conversations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  phone_number_id uuid,
  contact_id uuid,
  conversation_id character varying,
  origin_type character varying,
  expiration_timestamp timestamp with time zone,
  is_active boolean DEFAULT true,
  assigned_user_id uuid,
  status character varying DEFAULT 'active'::character varying,
  priority character varying DEFAULT 'normal'::character varying,
  labels ARRAY DEFAULT '{}'::text[],
  last_message_at timestamp with time zone,
  last_message_preview text,
  unread_count integer DEFAULT 0,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT whatsapp_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT whatsapp_conversations_assigned_user_id_fkey FOREIGN KEY (assigned_user_id) REFERENCES public.users(id),
  CONSTRAINT whatsapp_conversations_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.whatsapp_contacts(id),
  CONSTRAINT whatsapp_conversations_phone_number_id_fkey FOREIGN KEY (phone_number_id) REFERENCES public.whatsapp_phone_numbers(id)
);
CREATE TABLE public.whatsapp_media_files (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  media_id character varying NOT NULL UNIQUE,
  url text,
  mime_type character varying,
  sha256 character varying,
  file_size integer,
  local_path text,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT whatsapp_media_files_pkey PRIMARY KEY (id)
);
CREATE TABLE public.whatsapp_message_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  phone_number_id uuid,
  template_id character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  language character varying NOT NULL,
  category USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL,
  rejection_reason text,
  components jsonb NOT NULL,
  example jsonb,
  quality_score jsonb,
  previous_category character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT whatsapp_message_templates_pkey PRIMARY KEY (id),
  CONSTRAINT whatsapp_message_templates_phone_number_id_fkey FOREIGN KEY (phone_number_id) REFERENCES public.whatsapp_phone_numbers(id)
);
CREATE TABLE public.whatsapp_messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  conversation_id uuid,
  wamid character varying NOT NULL UNIQUE,
  type USER-DEFINED NOT NULL,
  from_number character varying NOT NULL,
  to_number character varying NOT NULL,
  timestamp timestamp with time zone NOT NULL,
  text_body text,
  text_preview_url boolean,
  media_id character varying,
  media_url text,
  media_mime_type character varying,
  media_sha256 character varying,
  media_file_size integer,
  media_caption text,
  media_filename character varying,
  location_latitude numeric,
  location_longitude numeric,
  location_name character varying,
  location_address character varying,
  location_url text,
  contacts_data jsonb,
  interactive_type character varying,
  interactive_data jsonb,
  template_name character varying,
  template_language character varying,
  template_namespace character varying,
  template_components jsonb,
  reaction_message_id character varying,
  reaction_emoji character varying,
  context_from character varying,
  context_message_id character varying,
  context_forwarded boolean DEFAULT false,
  context_frequently_forwarded boolean DEFAULT false,
  system_type character varying,
  system_body text,
  system_identity character varying,
  system_new_wa_id character varying,
  status USER-DEFINED,
  errors jsonb,
  referral jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT whatsapp_messages_pkey PRIMARY KEY (id),
  CONSTRAINT whatsapp_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.whatsapp_conversations(id)
);
CREATE TABLE public.whatsapp_phone_numbers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid,
  phone_number_id character varying NOT NULL UNIQUE,
  verified_name character varying,
  display_phone_number character varying,
  quality_rating character varying,
  messaging_limit_tier integer,
  max_daily_conversation_per_phone integer,
  is_pin_enabled boolean DEFAULT false,
  is_name_mismatch boolean DEFAULT false,
  name_status character varying,
  certificate text,
  code_verification_status character varying,
  eligibility_for_api_business boolean DEFAULT true,
  access_token text,
  webhook_verify_token character varying,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT whatsapp_phone_numbers_pkey PRIMARY KEY (id),
  CONSTRAINT whatsapp_phone_numbers_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.whatsapp_webhook_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  phone_number_id uuid,
  type USER-DEFINED NOT NULL,
  payload jsonb NOT NULL,
  processed boolean DEFAULT false,
  processed_at timestamp with time zone,
  error text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT whatsapp_webhook_events_pkey PRIMARY KEY (id),
  CONSTRAINT whatsapp_webhook_events_phone_number_id_fkey FOREIGN KEY (phone_number_id) REFERENCES public.whatsapp_phone_numbers(id)
);